### ISSUE TITLE
Calculate yaw angle form velocity change

### ISSUE THREAD

**Issue by Tao-wecorp** [kimbring2/DeepSoccer#6]
Hi, @kimbring2 

When we apply left_action or right_action = [40, -40], how can we calculate the yaw angle? 

Thanks
Tao

**Comment by kimbring2** [comment]
@Tao-wecorp Hi, Tao. Thank you for good question. You can check a position and orientation of robot using '/gazebo/model_states' msg. I think yaw angle is y value of orientation of msg.pose of each robot.

I add a some sample code for it. 

`
sub_state = rospy.Subscriber('/gazebo/model_states', ModelStates, state_callback)

def state_callback(msg):
    global state_j 
    global d
    robot1_index = (msg.name).index("robot1")
    robot1_pose = (msg.pose)[robot1_index]
    print("robot1_pose.: " + str(robot1_pose))

while not rospy.is_shutdown():
    robot1_action = robot_action_list[2]
    #print("robot1_action: " + str(robot1_action))

    pub_vel_left_1.publish(robot1_action[0])
    pub_vel_right_1.publish(robot1_action[1])
`

![Screenshot from 2020-04-11 16-23-04](https://user-images.githubusercontent.com/11064407/79037991-c4206600-7c10-11ea-9e08-ae51a7e678b0.png)

I wish you are safe from Virus.

Thank you, 
From Dohyeong

**Comment by Tao-wecorp** [comment]
@kimbring2 Thanks a lot! you keep safe too~
