### ISSUE TITLE
RLException Error (running source devel/setup.bash didn't help) 

### ISSUE THREAD

**Issue by leeorn** [kimbring2/DeepSoccer#7]
I followed the steps up to the ROS launch command (roslaunch jetbot_description jetbot_rviz.launch), and I got the same error as in the read me [RLException Error](https://github.com/kimbring2/DeepSoccer#rlexception-error). I re-ran source devel/setup.bash and tried again, but it didn't help.

Any ideas?

**Comment by kimbring2** [comment]
@leeorn Hi, Leeorn

It looks good idea running simple Gazebo project for checking which part is problem.

Can you try to run simple Gazebo project at 'http://gazebosim.org/tutorials?tut=ros_urdf'?

Please tell me error is still existed after doing it!!

Thank you,
From Dohyeong

**Comment by leeorn** [comment]
Hey @kimbring2. thank you. I deleted everything and did it again and it worked!

**Comment by kimbring2** [comment]
@leeorn That was great. Please ask question if another problem will arise.
