### ISSUE TITLE
CMake Error about gazebo_ros

### ISSUE THREAD

**Issue by kjwoo31** [kimbring2/DeepSoccer#9]
I have a problem with building the ROS project. I get an error message as below when I execute 'catkin_make'.
 I did it right after checking jetbot_ros in https://github.com/dusty-nv/jetbot_ros works well.
 I tried downloading gazebo-ros to fix this, but it didn't work. How can I solve this problem?

## error message
-- +++ processing catkin package: 'solenoid_electromagnet_joint_spring_plugin'
-- ==> add_subdirectory(DeepSoccer/solenoid_electromagnet_joint_spring_plugin)
-- Could NOT find gazebo_ros (missing: gazebo_ros_DIR)
-- Could not find the required component 'gazebo_ros'. The following CMake error indicates that you either need to install the package with the same name or change your environment so that it can be found.
CMake Error at /opt/ros/melodic/share/catkin/cmake/catkinConfig.cmake:83 (find_package):
  Could not find a package configuration file provided by "gazebo_ros" with
  any of the following names:

    gazebo_rosConfig.cmake
    gazebo_ros-config.cmake

  Add the installation prefix of "gazebo_ros" to CMAKE_PREFIX_PATH or set
  "gazebo_ros_DIR" to a directory containing one of the above files.  If
  "gazebo_ros" provides a separate development package or SDK, be sure it has
  been installed.
Call Stack (most recent call first):
  DeepSoccer/solenoid_electromagnet_joint_spring_plugin/CMakeLists.txt:5 (find_package)

-- Configuring incomplete, errors occurred!
See also "/home/jetbot/workspace/catkin_ws/build/CMakeFiles/CMakeOutput.log".
See also "/home/jetbot/workspace/catkin_ws/build/CMakeFiles/CMakeError.log".
Makefile:852: recipe for target 'cmake_check_build_system' failed
make: *** [cmake_check_build_system] Error 1
Invoking "make cmake_check_build_system" failed

**Comment by kjwoo31** [comment]
Solved by 

> sudo apt install ros-melodic-gazebo_ros

**Comment by kimbring2** [comment]
Hello,

The 'solenoid_electromagnet_joint_spring_plugin' package is for Gazebo simulation in Desktop. 

You need to use the 'https://github.com/kimbring2/DeepSoccer/tree/master/deepsoccer_ros' folder for your Jetson board. 

Sorry for the confusion.
